### ISSUE TITLE
Support metrics for Scaleway S3

### ISSUE THREAD

**Issue by ntimo** [promhippie/scw_exporter#15]
It would be super awesome if this exporter could be used to export metrics about the Scaleway S3 storage.

**Comment by tboerger** [comment]
Generally I'm really open for that, but in the meantime I anway wanted to restructure the repository a little bit. Since I'm fully into projects within my job and in my sparetime preparing for conference this will take some time.

**Comment by tboerger** [comment]
I wanted to provide this, but looks like this is not part of the current client provided by Scaleway.

**Comment by tboerger** [comment]
Since there are no client capabilities to provide these metrics I will close this feature request for now.
