### ISSUE TITLE
Add exposed port to dockerfiles

### ISSUE THREAD

**Issue by tboerger** [promhippie/scw_exporter#4]
Currently the dockerfiles are missing the exposed port, that got to be added.

**Comment by destag** [comment]
Can I take this one?

**Comment by tboerger** [comment]
Yeah, why not. Maybe you could do that for the hetzner and hcloud exporter as well?

All Dockerfiles are located within the docker/ folder.

**Comment by tboerger** [comment]
Ah and please add it above the entrypoint definition :)
